//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI_LINEBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDB()
        {
            this.information_OrderDB = new HashSet<information_OrderDB>();
        }
    
        public string Cus_ID { get; set; }
        public string Cus_Name { get; set; }
        public string Cus_Phone { get; set; }
        public string Cus_Password { get; set; }
        public string Cus_Sex { get; set; }
        public string Cus_Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<information_OrderDB> information_OrderDB { get; set; }
    }
}
