//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI_LINEBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverDB()
        {
            this.information_OrderDB = new HashSet<information_OrderDB>();
        }
    
        public int Dr_Num { get; set; }
        public string Dr_ID { get; set; }
        public string Dr_Name { get; set; }
        public string Dr_Phone { get; set; }
        public string Dr_Password { get; set; }
        public string Dr_Sex { get; set; }
        public string Dr_Photo { get; set; }
        public string Dr_License { get; set; }
        public string Dr_vehicle_license { get; set; }
        public string Dr_good_citizen { get; set; }
        public string Dr_taxi_driver_license { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<information_OrderDB> information_OrderDB { get; set; }
    }
}
